spring:
  cache:
    jcache:
      config: classpath:ehcache.xml

server:
  shutdown: graceful

management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

springdoc:
  use-fqn: true
  swagger-ui:
    enabled: false
  api-docs:
    path: api-docs

swaply:
  client:
    cnb:
      url: https://www.cnb.cz
      connection-timeout: 3000
      read-timeout: 3000
    currencylayer:
      url: https://apilayer.net/api
      connection-timeout: 3000
      read-timeout: 3000
      access-key: 25189bd1b995d3b8b726eebfddbf1604
