### Healthcheck endpoint
GET http://localhost:9000/actuator/health

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });

  client.test("Check status in response body", function() {
    client.assert(response.body.status === "UP", "Status is not UP");
  });
%}

### OPTIONS Swaply API documentation
OPTIONS http://localhost:8080/api-docs

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### UNAUTHORIZED Swaply API documentation
GET http://localhost:8080/api-docs

> {%
  client.test("Request unathorized", function() {
    client.assert(response.status === 401, "Response status is not 401");
  });
%}

### GET Swaply API documentation
@auth = YWRtaW46YWRtaW4=
GET http://localhost:8080/api-docs
Authorization: Basic {{auth}}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### Get currencies
GET http://localhost:8080/api/v1/exchange-rate/currency-pairs
Authorization: Basic {{auth}}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### Get exchange rates diff
@currencyPairCode = CZKHUF
GET http://127.0.0.1:8080/api/v1/exchange-rate/differences/{{currencyPairCode}}
Authorization: Basic {{auth}}

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}
